import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Download } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ChartCard, DemoDataNote } from "@/components/ChartCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  confidenceDistribution,
  digitizationActivity,
  DISTRICTS,
  documentTypeDistribution,
  DOC_TYPES,
  languageDistribution,
  recordsByDistrict,
  recordsByState,
  STATES,
  validationOverview,
} from "@/data/mockData";
import { toast } from "sonner";

export const Route = createFileRoute("/analytics")({
  head: () => ({
    meta: [
      { title: "Digitization Analytics — Digi Bhoomi" },
      {
        name: "description",
        content:
          "Interactive analytics for land record digitization: throughput, verification status, confidence distribution, document types and languages.",
      },
      { property: "og:title", content: "Digitization Analytics — Digi Bhoomi" },
      {
        property: "og:description",
        content:
          "Charts covering digitization throughput, confidence distribution and verification status.",
      },
    ],
  }),
  component: AnalyticsPage,
});

const COLORS = [
  "var(--color-chart-1)",
  "var(--color-chart-2)",
  "var(--color-chart-3)",
  "var(--color-chart-4)",
  "var(--color-chart-5)",
];

function AnalyticsPage() {
  const [from, setFrom] = useState("2026-03-01");
  const [to, setTo] = useState("2026-09-01");
  const [state, setState] = useState("all");
  const [district, setDistrict] = useState("all");
  const [docType, setDocType] = useState("all");
  const [language, setLanguage] = useState("all");

  return (
    <AppShell
      title="Analytics"
      description="Digitization, verification and extraction-quality analytics across states and districts."
      breadcrumb={[{ label: "Analytics" }]}
    >
      <div className="grid gap-3 rounded-lg border border-border bg-card p-4 shadow-card sm:grid-cols-2 xl:grid-cols-6">
        <div>
          <Label htmlFor="from" className="text-xs font-medium text-muted-foreground">
            From
          </Label>
          <Input
            id="from"
            type="date"
            value={from}
            onChange={(e) => setFrom(e.target.value)}
            className="mt-1.5"
          />
        </div>
        <div>
          <Label htmlFor="to" className="text-xs font-medium text-muted-foreground">
            To
          </Label>
          <Input
            id="to"
            type="date"
            value={to}
            onChange={(e) => setTo(e.target.value)}
            className="mt-1.5"
          />
        </div>
        <Filter label="State" value={state} onChange={setState} options={STATES} />
        <Filter label="District" value={district} onChange={setDistrict} options={DISTRICTS} />
        <Filter label="Document Type" value={docType} onChange={setDocType} options={DOC_TYPES} />
        <Filter
          label="Language"
          value={language}
          onChange={setLanguage}
          options={["Hindi", "English", "Other Indian Language"]}
        />
        <div className="sm:col-span-2 xl:col-span-6">
          <Button
            variant="outline"
            size="sm"
            onClick={() =>
              toast.success("Report export queued", {
                description: "Demo export — no file is generated by the backend yet.",
              })
            }
          >
            <Download className="mr-1.5 h-4 w-4" aria-hidden /> Export Report
          </Button>
        </div>
      </div>

      <DemoDataNote className="mt-4" />

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <ChartCard
          title="Records Digitized Over Time"
          description="Monthly digitization throughput (demo)."
        >
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={digitizationActivity} margin={{ left: -18, right: 8, top: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis
                dataKey="month"
                tick={{ fontSize: 12 }}
                stroke="var(--color-muted-foreground)"
              />
              <YAxis tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Area
                type="monotone"
                dataKey="processed"
                name="Processed"
                stroke="var(--color-chart-1)"
                fill="var(--color-chart-1)"
                fillOpacity={0.15}
                strokeWidth={2}
              />
            </AreaChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard
          title="Verification Status"
          description="Share of records by verification state (demo)."
        >
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie data={validationOverview} dataKey="value" nameKey="name" outerRadius={95}>
                {validationOverview.map((e, i) => (
                  <Cell key={e.key} fill={COLORS[i % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Legend wrapperStyle={{ fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Records by State" description="State-wise digitized volume (demo).">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={recordsByState} margin={{ left: -18, right: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis
                dataKey="name"
                tick={{ fontSize: 10 }}
                angle={-18}
                textAnchor="end"
                height={54}
                interval={0}
                stroke="var(--color-muted-foreground)"
              />
              <YAxis tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Bar
                dataKey="value"
                name="Records"
                fill="var(--color-chart-1)"
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Records by District" description="District-wise digitized volume (demo).">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={recordsByDistrict} layout="vertical" margin={{ left: 24, right: 12 }}>
              <CartesianGrid
                strokeDasharray="3 3"
                stroke="var(--color-border)"
                horizontal={false}
              />
              <XAxis type="number" tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <YAxis
                type="category"
                dataKey="name"
                width={100}
                tick={{ fontSize: 11 }}
                stroke="var(--color-muted-foreground)"
              />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Bar
                dataKey="value"
                name="Records"
                fill="var(--color-chart-5)"
                radius={[0, 4, 4, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard
          title="Confidence Distribution"
          description="Extraction confidence buckets (demo)."
        >
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={confidenceDistribution} margin={{ left: -18, right: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis
                dataKey="range"
                tick={{ fontSize: 12 }}
                stroke="var(--color-muted-foreground)"
              />
              <YAxis tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Bar dataKey="value" name="Records" radius={[4, 4, 0, 0]}>
                {confidenceDistribution.map((entry, i) => (
                  <Cell
                    key={entry.range}
                    fill={
                      i < 2
                        ? "var(--color-success)"
                        : i < 4
                          ? "var(--color-warning)"
                          : "var(--color-destructive)"
                    }
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Document Type Distribution" description="Source document mix (demo).">
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie
                data={documentTypeDistribution}
                dataKey="value"
                nameKey="name"
                innerRadius={50}
                outerRadius={90}
              >
                {documentTypeDistribution.map((e, i) => (
                  <Cell key={e.name} fill={COLORS[i % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Legend wrapperStyle={{ fontSize: 11 }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Language Distribution" description="Detected source languages (demo).">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={languageDistribution} margin={{ left: -18, right: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis
                dataKey="name"
                tick={{ fontSize: 11 }}
                stroke="var(--color-muted-foreground)"
              />
              <YAxis tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Bar
                dataKey="value"
                name="Records"
                fill="var(--color-chart-2)"
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Processing Status" description="Pipeline stage occupancy (demo).">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart
              data={[
                { name: "Queued", value: 37 },
                { name: "OCR", value: 18 },
                { name: "Classification", value: 12 },
                { name: "Validation", value: 21 },
                { name: "Awaiting Review", value: 64 },
              ]}
              margin={{ left: -18, right: 8 }}
            >
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis
                dataKey="name"
                tick={{ fontSize: 11 }}
                stroke="var(--color-muted-foreground)"
              />
              <YAxis tick={{ fontSize: 12 }} stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{ borderRadius: 8, borderColor: "var(--color-border)", fontSize: 12 }}
              />
              <Bar
                dataKey="value"
                name="Documents"
                fill="var(--color-chart-3)"
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>
    </AppShell>
  );
}

function Filter({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: string[];
}) {
  const id = `analytics-${label.toLowerCase().replace(/\s+/g, "-")}`;
  return (
    <div className="min-w-0">
      <Label htmlFor={id} className="text-xs font-medium text-muted-foreground">
        {label}
      </Label>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger id={id} className="mt-1.5 w-full">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="all">All</SelectItem>
          {options.map((o) => (
            <SelectItem key={o} value={o}>
              {o}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
}
