/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsIdRouteImport } from './routes/records.$id'
import { Route as VerificationIndexRouteImport } from './routes/verification.index'
import { Route as VerificationIdRouteImport } from './routes/verification.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIdRoute = VerificationIdRouteImport.update({
  id: '/verification/$id',
  path: '/verification/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/records/$id': typeof RecordsIdRoute
  '/verification/$id': typeof VerificationIdRoute
  '/records/': typeof RecordsIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/records/$id': typeof RecordsIdRoute
  '/verification/$id': typeof VerificationIdRoute
  '/records': typeof RecordsIndexRoute
  '/verification': typeof VerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/records/$id': typeof RecordsIdRoute
  '/verification/$id': typeof VerificationIdRoute
  '/records/': typeof RecordsIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/reports'
    | '/settings'
    | '/upload'
    | '/records/$id'
    | '/verification/$id'
    | '/records/'
    | '/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/reports'
    | '/settings'
    | '/upload'
    | '/records/$id'
    | '/verification/$id'
    | '/records'
    | '/verification'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/map'
    | '/reports'
    | '/settings'
    | '/upload'
    | '/records/$id'
    | '/verification/$id'
    | '/records/'
    | '/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  RecordsIdRoute: typeof RecordsIdRoute
  VerificationIdRoute: typeof VerificationIdRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  VerificationIndexRoute: typeof VerificationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/': {
      id: '/verification/'
      path: '/verification'
      fullPath: '/verification/'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/$id': {
      id: '/verification/$id'
      path: '/verification/$id'
      fullPath: '/verification/$id'
      preLoaderRoute: typeof VerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  RecordsIdRoute: RecordsIdRoute,
  VerificationIdRoute: VerificationIdRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  VerificationIndexRoute: VerificationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
